namespace API_Bus_Ticket_Booking.DTOs.Review;

public class ReviewCreateDto
{
    // No customer_id or review_id?
    // customer_id will be taken from url
    // review_id will be generated by the server
    public int TripId { get; set; }
    public int Rating { get; set; } // 1 - 5
    public string? Comment { get; set; }
}
